# ===========================================
# Test Profile
# ===========================================

server:
  port: 8081

spring:

  jpa:
    hibernate:
      ddl-auto: create-drop

# Logging - 테스트 환경
logging:
  level:
    root: INFO
    com.umc.devine: DEBUG
    org.hibernate.SQL: DEBUG
