spring:
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    active: dev
  application:
    name: DeVine

  # OAuth2 (Clerk JWT)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URI:}

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:}:${POSTGRES_PORT:}/${POSTGRES_DATABASE:}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  # Redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2000ms}

  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Clerk
clerk:
  secret-key: ${CLERK_SECRET_KEY:}

# GitHub
github:
  service-token: ${GITHUB_SERVICE_TOKEN:}